use customer_behavior;


-- Q1. What is the total revenue generated by male vs female customer?

select gender , sum(purchase_amount) as revenue from customer group by gender;

-- Q2. Which customer used a  discount but still spent more than a average purchase amount?

select customer_id,purchase_amount from customer 
where discount_applied = 'Yes'and
purchase_amount >=(select avg(purchase_amount) as Avg_purchase_amount from customer);

-- Q3.Which are the top 5 products with the highest average review rating ?

select item_purchased , round(avg(review_rating),2) as Avg_rating  from customer 
group by item_purchased 
order by Avg_rating Desc 
LIMIT 5;

-- Q4.Compare the average purchase amounts between Standard and Express Shipping ?

SELECT shipping_type,round(AVG(purchase_amount),2)  AS Avg_Purchase_amount from customer 
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more ? compare average spend and total revenue 
---- between subscribers and non-subscribers.

select subscription_status ,count(customer_id) as total_customer,
round(AVG(purchase_amount),2) AS Avg_Purchase_amount ,
round(sum(purchase_amount),2) AS Total_spent_amount 
from customer 
group by subscription_status ;

-- Q6.Which 5 products have the highest percentage of purchases with discount applied?

select item_purchased ,
ROUND(100 * sum(case when discount_applied = 'Yes' THEN 1 ELSE 0 END )/count(discount_applied),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7.Segment customers into New , Returning, and Loyol based on their totol no.of previous purchases
-- and show the count of each segment ?

with customer_type as (
select customer_id,previous_purchases,
case 
when previous_purchases = 1 then  'New'
when previous_purchases between 2 and 10 then 'returning'
else 'Loyal'
End as customer_segment from customer)
select customer_segment, count(*) as "Number of customers"
from customer_type group by customer_segment;


-- Q8.Segment customers into New , Returning, and Loyol based on their totol no.of previous purchases
-- and show the count of each segment ?

with items_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer 
group by category, item_purchased )

select item_rank , category, item_purchased, total_orders from items_count 
where item_rank <= 3;

-- Q9.Are customers who are  repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status;

-- Q10.What is the revenue contribution of each age group?

select * from customer;
select age_group , sum(purchase_amount) as Total_revenue from customer group by age_group;
